/* 
 * File:   mcal_interrupt_gen_cfg.h
 * Author: omar fathy
 *
 * Created on 30 June 2024, 12:32
 */

#ifndef MCAL_INTERRUPT_GEN_CFG_H
#define	MCAL_INTERRUPT_GEN_CFG_H

/* INCLUDES */

 
/* MACRO DECLARATIONS */
#define INTERRUPT_FEATURE_ENABLE  1U
//#define INTERRUPT_PRIORITY_LEVELS_ENABLE              INTERRUPT_FEATURE_ENABLE
#define EXTERNAL_INTERRUPT_INTx_FEATURE_ENABLE        INTERRUPT_FEATURE_ENABLE
#define EXTERNAL_INTERRUPT_OnChange_FEATURE_ENABLE    INTERRUPT_FEATURE_ENABLE

/* MACRO FUNCTIONS DECLARATIONS */


/* DATA TYPES DECLARATIONS */


/* FUNCTIONS DECLARATIONS */


#endif	/* MCAL_INTERRUPT_GEN_CFG_H */

